//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportKIP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImportKIP.Resources.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего в таблице.
        /// </summary>
        public static string AllTable {
            get {
                return ResourceManager.GetString("AllTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Attantion {
            get {
                return ResourceManager.GetString("Attantion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическая увязка КИП.
        /// </summary>
        public static string AutomaticLinkingKIP {
            get {
                return ResourceManager.GetString("AutomaticLinkingKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуть скрытые строки.
        /// </summary>
        public static string BuBDAdd {
            get {
                return ResourceManager.GetString("BuBDAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать выделенные строки.
        /// </summary>
        public static string BuBDDelete {
            get {
                return ResourceManager.GetString("BuBDDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импортировать.
        /// </summary>
        public static string BuImport {
            get {
                return ResourceManager.GetString("BuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление увязанных КИП.
        /// </summary>
        public static string DeletingLinkedKIP {
            get {
                return ResourceManager.GetString("DeletingLinkedKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление данных предыдущего импорта.
        /// </summary>
        public static string DeletingPreviousImport {
            get {
                return ResourceManager.GetString("DeletingPreviousImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файла в базу данных.
        /// </summary>
        public static string DownloadFileInDatabase {
            get {
                return ResourceManager.GetString("DownloadFileInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При загрузке файла на сервер возникла ошибка, не найден путь к каталогу..
        /// </summary>
        public static string ErrorFile {
            get {
                return ResourceManager.GetString("ErrorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При импорте произошла ошибка..
        /// </summary>
        public static string ErrorImport {
            get {
                return ResourceManager.GetString("ErrorImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Километраж, км.
        /// </summary>
        public static string GridBDKM {
            get {
                return ResourceManager.GetString("GridBDKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string GridBDName {
            get {
                return ResourceManager.GetString("GridBDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип КИП.
        /// </summary>
        public static string GridBDType {
            get {
                return ResourceManager.GetString("GridBDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        public static string GridFilePrim {
            get {
                return ResourceManager.GetString("GridFilePrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U пол, В.
        /// </summary>
        public static string GridFileUp {
            get {
                return ResourceManager.GetString("GridFileUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U т-з, В.
        /// </summary>
        public static string GridFileUt {
            get {
                return ResourceManager.GetString("GridFileUt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор участка.
        /// </summary>
        public static string GroupBox1 {
            get {
                return ResourceManager.GetString("GroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите данные....
        /// </summary>
        public static string GroupBox1ComboBox {
            get {
                return ResourceManager.GetString("GroupBox1ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string GroupBox1Data {
            get {
                return ResourceManager.GetString("GroupBox1Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МГ.
        /// </summary>
        public static string GroupBox1MG {
            get {
                return ResourceManager.GetString("GroupBox1MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нить.
        /// </summary>
        public static string GroupBox1Thread {
            get {
                return ResourceManager.GetString("GroupBox1Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные по выбранному участку.
        /// </summary>
        public static string GroupBox2 {
            get {
                return ResourceManager.GetString("GroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало, км.
        /// </summary>
        public static string GroupBox2Begin {
            get {
                return ResourceManager.GetString("GroupBox2Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец, км.
        /// </summary>
        public static string GroupBox2End {
            get {
                return ResourceManager.GetString("GroupBox2End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина, км.
        /// </summary>
        public static string GroupBox2Length {
            get {
                return ResourceManager.GetString("GroupBox2Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В таблице КИП из файла скрыты выбранные строки (показаны скрытые).
        /// </summary>
        public static string HideOrShowKIP {
            get {
                return ResourceManager.GetString("HideOrShowKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт завершен.
        /// </summary>
        public static string ImportEnd {
            get {
                return ResourceManager.GetString("ImportEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сезонные измерения импортируются в базу данных, создаются паспорта.
        /// </summary>
        public static string ImportKIP {
            get {
                return ResourceManager.GetString("ImportKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыто.
        /// </summary>
        public static string InVisible {
            get {
                return ResourceManager.GetString("InVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИП из БД.
        /// </summary>
        public static string KIPBD {
            get {
                return ResourceManager.GetString("KIPBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИП из файла импорта.
        /// </summary>
        public static string KIPFILE {
            get {
                return ResourceManager.GetString("KIPFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическая увязка завершена.
        /// </summary>
        public static string LinkGood {
            get {
                return ResourceManager.GetString("LinkGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение таблицы сопоставленных данных.
        /// </summary>
        public static string LinkingKIP {
            get {
                return ResourceManager.GetString("LinkingKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка результатов анализа файла.
        /// </summary>
        public static string LoadingDataLog {
            get {
                return ResourceManager.GetString("LoadingDataLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка списка журналов сезонных измерений.
        /// </summary>
        public static string LoadingListOfJournalsKIP {
            get {
                return ResourceManager.GetString("LoadingListOfJournalsKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение таблицы КИП из БД.
        /// </summary>
        public static string LoadingListOfKipFromDatabase {
            get {
                return ResourceManager.GetString("LoadingListOfKipFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение таблицы КИП из файла.
        /// </summary>
        public static string LoadingListOfKipFromFile {
            get {
                return ResourceManager.GetString("LoadingListOfKipFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка списка увязанных КИП.
        /// </summary>
        public static string LoadingListOfLinkedKIP {
            get {
                return ResourceManager.GetString("LoadingListOfLinkedKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка списка магистральных газопроводов.
        /// </summary>
        public static string LoadingListOfMG {
            get {
                return ResourceManager.GetString("LoadingListOfMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка списка нитей.
        /// </summary>
        public static string LoadingListOfThreads {
            get {
                return ResourceManager.GetString("LoadingListOfThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка характеристик участка.
        /// </summary>
        public static string LoadingSettingsOfSite {
            get {
                return ResourceManager.GetString("LoadingSettingsOfSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставленные данные.
        /// </summary>
        public static string Mapped1 {
            get {
                return ResourceManager.GetString("Mapped1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Километраж, км (БД).
        /// </summary>
        public static string MappedKMBD {
            get {
                return ResourceManager.GetString("MappedKMBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Километраж, км (файл).
        /// </summary>
        public static string MappedKMFile {
            get {
                return ResourceManager.GetString("MappedKMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (БД).
        /// </summary>
        public static string MappedNameBD {
            get {
                return ResourceManager.GetString("MappedNameBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (файл).
        /// </summary>
        public static string MappedNameFile {
            get {
                return ResourceManager.GetString("MappedNameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны КИП.
        /// </summary>
        public static string NoSelectKIP {
            get {
                return ResourceManager.GetString("NoSelectKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты анализа файла....
        /// </summary>
        public static string ResultUploadFile {
            get {
                return ResourceManager.GetString("ResultUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл....
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шт..
        /// </summary>
        public static string Sh {
            get {
                return ResourceManager.GetString("Sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязать вручную.
        /// </summary>
        public static string Uv1 {
            get {
                return ResourceManager.GetString("Uv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить без увязывания.
        /// </summary>
        public static string Uv2 {
            get {
                return ResourceManager.GetString("Uv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить автоматическое увязывание.
        /// </summary>
        public static string Uv3 {
            get {
                return ResourceManager.GetString("Uv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить увязывание.
        /// </summary>
        public static string Uv4 {
            get {
                return ResourceManager.GetString("Uv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязано.
        /// </summary>
        public static string UvAll {
            get {
                return ResourceManager.GetString("UvAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенесено без увязки.
        /// </summary>
        public static string UvNo {
            get {
                return ResourceManager.GetString("UvNo", resourceCulture);
            }
        }
    }
}
